### PR TITLE
fix(transformData): always call transformData

### LINKED ISSUE #1538: Bug: Hit not re-rendered when you modify the data in transformData
When making two queries that return the same hit, but this hit is handled differently in transformData between the first and second query, the hit component won't be re-rendered.

Apparently, that comes from the fact that `shouldComponentUpdate` is based on the data retrieved by the API instead of the data sent after `transformData`.

An easy way to reproduce this is to add a timestamp to the hit object in `transformData`, and display it in the component.

### PR DESCRIPTION
**Pull request by vvo**
Summary:
Even when data does not changes, we now call transformData. So that
if the transformed data changes, there will be a new render call.

fixes #1538
linked to #1100

### CODE REVIEW

File: src/components/Template.js [hunk 1]
```diff
@@ -137,4 +137,15 @@ function transformHelpersToHogan(helpers, compileOptions, data) {
   );
 }
 
-export default Template;
+// Resolve transformData before Template, so transformData is always called
+// even if the data is the same. Allowing you to dynamically inject conditions in
+// transformData that will force re-rendering
+const withTransformData =
```
Comment (vvo) [inline src/components/Template.js]: This is the interesting part

File: src/widgets/refinement-list/__tests__/refinement-list-test.js [hunk 2]
```diff
@@ -187,17 +179,6 @@ describe('refinementList()', () => {
       createURL = () => '#';
     });
 
-    it('formats counts', () => {
```
Comment (vvo) [inline src/widgets/refinement-list/__tests__/refinement-list-test.js]: This is not the place to test this, applied helpers are already tested in Template-test

File: src/components/Template.js (hunk 1 above)
Comment (bobylito) [inline src/components/Template.js]: Have you considered using alternative implementations? What about use transformData in willReceiveProps and store the result in the state?

**Comment by vvo** [comment]
> Just wondering if we could have not used a HOC for that.

Indeed this complexifies a bit the code, I will have a look at your idea using the state, wonder if any drawbacks.
