### PR TITLE
fix(routing): apply windowTitle on first load

### LINKED ISSUE #3667: windowTitle does not trigger when page loads
**Describe the bug 🐛**
The `windowTitle` option for routing does not trigger when the page first loads.

**To Reproduce 🔍**
This issue can be easily reproduced via official SEO friendly URLs demo

1. Open demo via [CodeSandbox](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/InstantSearch.js/routing-seo-friendly)
2. Run the demo and click "Open in New Window"
3. Type something to search, notice the title change
4. Refresh the page using browser reload.
5. Title does not change.

**Expected behavior 💭**
The page title should contains correct queries from `windowTitle` after page reload.

**Screencast 🎬**
https://www.useloom.com/share/96c3c8f3329041c7bc6d74e232812ad4

**Environment:**
 - OS: macOS
 - Browser: Google Chrome
 - Version: 73.0.3683.86

**Additional context**

### PR DESCRIPTION
**Pull request by francoischalifour**
_This PR is a fix for #3667._

The [`windowTitle`](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/js/#windowtitle-functionroutestate-string) param of the routing option didn't apply on the first page load. 

I fixed this by setting the document title also in the `RoutingManager` constructor, based on the URL query parameters which represent the route state.

This feature remained untested so I added a test for the first page load.

Note that Jest doesn't support updating `window.location` in tests (see facebook/jest#890 and facebook/jest#5124). I therefore needed to introduce two new JSDom dev dependencies to change `window.location` in separate tests, which give access to `jsdom.reconfigure({ url })`. I believe these dependencies will be needed in the feature while we refactor/test/reimplement the routing option.

The [Jest team has at some point considered giving access to `reconfigure`](https://github.com/facebook/jest/issues/890#issuecomment-352585259). This would mean that the new dependencies become unnecessary.

Closes #3667.

### CODE REVIEW

File: src/lib/__tests__/RoutingManager-test.js [hunk 1]
```diff
@@ -545,4 +547,54 @@ describe('RoutingManager', () => {
...
+    let setWindowTitle = jest.fn();
+
+    Object.defineProperty(window.document, 'title', {
+      get() {
+        return '';
+      },
+      set(value) {
+        setWindowTitle(value);
+      },
+    });
```
Comment (tkrugg) [inline src/lib/__tests__/RoutingManager-test.js]: There is an easier way to mock getters/setters
https://jestjs.io/docs/en/jest-object.html#jestspyonobject-methodname-accesstype

The nice thing about this way, is that you can later restore the mock, which you don't at the moment.

Comment (francoischalifour) [reply src/lib/__tests__/RoutingManager-test.js]: That's great, I didn't think of this usage. Thanks!

File: src/lib/routers/history.js [hunk 2]
```diff
@@ -44,6 +50,13 @@ class BrowserHistory {
     this.writeDelay = writeDelay;
     this._createURL = createURL;
     this.parseURL = parseURL;
+
+    const routeState = this.parseURL({
```
Comment (samouss) [inline src/lib/routers/history.js]: You can directly call `this.read()` it would avoid to duplicate the call.

File: src/lib/routers/history.js [hunk 3]
```diff
@@ -44,6 +50,13 @@ class BrowserHistory {
...
+      qsModule: qs,
+      location: window.location,
+    });
+    const title = this.windowTitle && this.windowTitle(routeState);
```
Comment (samouss) [inline src/lib/routers/history.js]: You can inline the call `this.read()` inside `this.windowTitle` (or make a condition) to avoid a useless parse when `windowTitle` is not provided.

File: src/lib/routers/history.js [hunk 4]
```diff
@@ -15,6 +15,12 @@ function defaultParseURL({ qsModule, location }) {
   return qsModule.parse(location.search.slice(1));
 }
 
+function setWindowTitle(title) {
+  if (title) {
+    window.document.title = title;
```
Comment (Haroenv) [inline src/lib/routers/history.js]: we aren't checking that these variables are available, however that's the same in other parts of this module too

Comment (samouss) [reply src/lib/routers/history.js]: You mean `window`?

File: src/lib/routers/history.js [hunk 5]
```diff
@@ -44,6 +50,9 @@ class BrowserHistory {
     this.writeDelay = writeDelay;
     this._createURL = createURL;
     this.parseURL = parseURL;
+
+    const title = this.windowTitle && this.windowTitle(this.read());
```
Comment (samouss) [inline src/lib/routers/history.js]:
```suggestion
    const title = this.windowTitle && this.windowTitle(this.read());
    
```

File: src/lib/routers/history.js (hunk 4 above)
Comment (Haroenv) [reply src/lib/routers/history.js]: yes, if window is not defined (i.e. in server side rendering) this code will throw

Comment (francoischalifour) [reply src/lib/routers/history.js]: We've got at least two more occurrences of `window` without check:

- https://github.com/algolia/instantsearch.js/blob/577e4ccb33155d0d4678b04505132d39a2918f22/src/connectors/numeric-menu/connectNumericMenu.js#L133
- https://github.com/algolia/instantsearch.js/blob/577e4ccb33155d0d4678b04505132d39a2918f22/src/widgets/analytics/analytics.js#L176

We can handle those when we plan to be SSR-ready.

File: src/lib/__tests__/RoutingManager-test.js [hunk 6]
```diff
@@ -1,5 +1,7 @@
+/* globals jsdom */
```
Comment (tkrugg) [inline src/lib/__tests__/RoutingManager-test.js]: what is this used for? looks like your tests are passing without it.

Comment (francoischalifour) [reply src/lib/__tests__/RoutingManager-test.js]: `jest-environment-jsdom-global` makes `jsdom` available in our tests ([read more](https://github.com/simon360/jest-environment-jsdom-global#readme)). However, ESLint is not aware of this global variable because this is not part of [`eslint-plugin-jest`](https://github.com/jest-community/eslint-plugin-jest).
