### PR TITLE
fix(template): transformData checks too strict

### LINKED ISSUE #347: Issue with transformData and no results
error thrown:  transformData` must return a `object`, got `undefined` 

working: no transform data function
working: transform data function + there is results
not working: transform data function + there is no result

Steps to reproduce:

Just add this to the hits widget in the example app
```
transformData: {
      item: function (hit) {
        return hit;
      }
}
```

### PR DESCRIPTION
**Pull request by redox**
The Template component shouldn't throw an error if you define
the transformData for a single templateKey.

Fix #347

### CODE REVIEW

**Comment by vvo** [comment]
I have trouble understanding the fix + the test given the bug explanation:

> not working: transform data function + there is no result
     
> Just add this to the hits widget in the example app
> item: function (hit) {
>     return hit;
>    }

File: components/Template.js [hunk 1]
```diff
@@ -67,7 +67,13 @@ function transformData(fn, templateKey, originalData) {
     data = fn(originalData);
   } else if (typeof fn === 'object') {
     // ex: transformData: {hit, empty}
-    data = fn[templateKey] && fn[templateKey](originalData);
```
Comment (bobylito) [inline components/Template.js]: `data = fn[templateKey] && fn[templateKey](originalData) || originalData`, no? :) Even if it does what we want it would less explicit ;)

Comment (redox) [inline components/Template.js]: Yes it was like that before but I prefer to split it and add an explicit comment.

**Comment by redox** [comment]
> I have trouble understanding the fix + the test given the bug explanation:

Using `transformData` with object should not impact the non-specified template keys. Here it was used with `{hit: fn}` but then the `empty` function wasn't found while generating the `empty` templateKey:  therefore we threw an exception. I introduced the bug in https://github.com/algolia/instantsearch.js/pull/213
