### PR TITLE
fix(api): rename hideContainerWhenNoResults to autoHideContainer

### LINKED ISSUE #407: rename hideContainerWhenNoResults to autoHideContainer
As proposed by @Jerskouille in #394 

TODO:
- [x] always use facet values count to hide the container when relevant
- [x] use nbHits if facet values not relevant
- [x] handle cases were we have only null facet values
- [x] also to be used in #405 clearAll proposals where we hide when no refinements WERE made (vs no facet values available in the algolia response)

### PR DESCRIPTION
**Pull request by vvo**
Mostly copy pasting

+ updated jsdoc
+ updated some widgets algorithm to hide/show (numeric widgets)
+ had to rename the decorators require to $decoratorHOC (High Order
Component, the pattern we use).

fixes #407

BREAKING CHANGE: use autoHideContainer instead of
hideContainerWhenNoResults

### CODE REVIEW

**Comment by vvo** [comment]
@Jerskouille ?

**Comment by bobylito** [comment]
:+1: LGTM

**Comment by Jerskouille** [comment]
:+1:

File: widgets/numeric-refinement-list/numeric-refinement-list.js [hunk 1]
```diff
@@ -72,7 +72,7 @@ function numericRefinementList({
         return option;
       });
 
-      let hasNoResults = facetValues.length === 0;
+      let hasNoResults = results.nbHits === 0;
```
Comment (Jerskouille) [inline widgets/numeric-refinement-list/numeric-refinement-list.js]: Shouldn't it be `facetValues` ?

Comment (vvo) [inline widgets/numeric-refinement-list/numeric-refinement-list.js]: No because the facetValues are manually set thus they are always here (you always have facetValues)
