### PR TITLE
fix(configure): pass the latest state to onStateChange

### LINKED ISSUE #4421: onStateChange with outdated uiState
## 🐛 Bug description

`onStateChange` doesn't receive the latest uiState when it's refined from connectConfigure.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to https://codesandbox.io/s/friendly-wozniak-48i5g?file=/src/app.js
2. Click on "click me" button
3. See the console log
4. Check the `configure` key has empty object as a value. (It's supposed to be `configure: { hitsPerPage: 4 }`

**Live reproduction:**

https://codesandbox.io/s/friendly-wozniak-48i5g?file=/src/app.js

## 💭 Expected behavior

It should deliver the latest uiState.

## Environment

- OS: macOS 10.15.3
- Browser: Firefox 76.0.1 (64-bit)

### PR DESCRIPTION
**Pull request by eunjae-lee**
**Summary**

This PR fixes the bug `configure` connector didn't pass the latest state to `onStateChange` when `refine` happened from it.

fixes #4421

**Result**

`onStateChange` receives the latest state. It's addressed in the integration test.

### CODE REVIEW

File: src/lib/__tests__/InstantSearch-integration-test.ts [hunk 1]
```diff
@@ -0,0 +1,46 @@
+import { getByText, fireEvent } from '@testing-library/dom';
```
Comment (Haroenv) [inline src/lib/__tests__/InstantSearch-integration-test.ts:1]: I think this file should just be called `InstantSearch-integration`, it's already in a tests folder

File: src/lib/__tests__/InstantSearch-integration-test.ts [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+import instantsearch from '../../index.es';
+import { configure } from '../../widgets';
+import { connectConfigure } from '../../connectors';
+import { createSearchClient } from '../../../test/mock/createSearchClient';
+
+describe('InstantSearch integration', () => {
+  it('renders', () => {
```
Comment (Haroenv) [inline src/lib/__tests__/InstantSearch-integration-test.ts:8]: test name should be about configure & onStateChange

**Comment by Haroenv** [comment]
You don't seem to have changed anything related to search state, how does this fix work?

File: src/lib/__tests__/InstantSearch-integration-test.ts (hunk 2 above)
Comment (eunjae-lee) [reply src/lib/__tests__/InstantSearch-integration-test.ts:8]: oops, it was a temporary name. will fix it

File: src/connectors/configure/connectConfigure.ts [hunk 3]
```diff
@@ -88,11 +88,11 @@ const connectConfigure: ConfigureConnector = function connectConfigure(
...
         );
 
-        // Trigger a search with the resolved search parameters
-        helper.setState(nextSearchParameters).search();
-
         // Update original `widgetParams.searchParameters` to the new refined one
         widgetParams.searchParameters = searchParameters;
+
+        // Trigger a search with the resolved search parameters
+        helper.setState(nextSearchParameters).search();
```
Comment (eunjae-lee) [inline src/connectors/configure/connectConfigure.ts:95]: When `search` happens, it will trigger `onStateChange`.

image

Before this change, the `widgetParams` was outdated at this point, now it's updated first, then the search is triggered.

File: src/lib/__tests__/InstantSearch-integration-test.ts (hunk 1 above)
Comment (eunjae-lee) [reply src/lib/__tests__/InstantSearch-integration-test.ts:1]: I cannot find it...?

File: src/lib/__tests__/InstantSearch-integration-test.ts (hunk 2 above)
Comment (eunjae-lee) [reply src/lib/__tests__/InstantSearch-integration-test.ts]: https://github.com/algolia/instantsearch.js/pull/4555/commits/da451436ec545b5d724681014abd2bdc31e1440c

File: src/lib/__tests__/InstantSearch-integration-test.ts (hunk 1 above)
Comment (shortcuts) [reply src/lib/__tests__/InstantSearch-integration-test.ts:1]: I think he meant to rename `InstantSearch-integration-test.ts` to `InstantSearch-integration.ts`

Comment (eunjae-lee) [reply src/lib/__tests__/InstantSearch-integration-test.ts:1]: Ah right. I misunderstood. I was looking for `InstantSearch-integration.ts` file.
But the thing is, all our test files end with `-test.*` in `__tests__`.

Comment (Haroenv) [reply src/lib/__tests__/InstantSearch-integration-test.ts:1]: ah I didn't notice that, fine for me then 👍

**Review by Haroenv — APPROVED** [review]

**Comment by francoischalifour** [comment]
Nice fix!
