### PR TITLE
fix(insights): send view events after rendering

### LINKED ISSUE #5013: Sending events to Insights middleware too early in connectHit
## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to https://codesandbox.io/s/laughing-kare-d7e0bo?file=/src/app.js
2. Search for `e`
3. Check the console log
4. When `onEvent` of Insights middleware is triggered, DOM is not updated yet, while `hits` passed from `connectHits` are up-to-date.

**Live reproduction:**

https://codesandbox.io/s/laughing-kare-d7e0bo?file=/src/app.js

## 💭 Expected behavior

https://github.com/algolia/instantsearch.js/blob/9209954594b048e9db3a91490002ae75522bceb2/src/connectors/hits/connectHits.ts#L107

↑ When you look at the code, the connector sends event before rendering. Although it passes the correct `hits` along with the event, but the DOM isn't up-to-date.

I think it can simply be like the following.

```diff
-       renderState.sendEvent('view', renderState.hits);

        renderFn(
          {
            ...renderState,
            instantSearchInstance: renderOptions.instantSearchInstance,
          },
          false
        );

+       renderState.sendEvent('view', renderState.hits);
```

https://codesandbox.io/s/objective-haze-25e8fi?file=/src/app.js

↑ this is a modified version, where `onEvent` is called after rendering.

## Context

This was discovered in the context of Google Tag Manager. On the GTM doc, we guide to use Insights middleware as "Hits Viewed" hook. When it's triggered, it notifies GTM so that it can track events. However, at that time, the DOM isn't up-to-date, so it went wrong.

### PR DESCRIPTION
**Pull request by eunjae-lee**
**Summary**

This PR fixes the order of sending view events and rendering in connectors.

fixes #5013

**Result**

At the time of view events being sent, the DOM is already updated.

### CODE REVIEW

File: src/connectors/hits/__tests__/connectHits-test.ts [hunk 1]
```diff
@@ -781,6 +781,55 @@ See documentation: https://www.algolia.com/doc/api-reference/widgets/hits/js/#co
...
+          const lastInvocationCallOrder = (mockFn: jest.Mock): number =>
+            mockFn.mock.invocationCallOrder[
+              mockFn.mock.invocationCallOrder.length - 1
+            ];
+
+          expect(lastInvocationCallOrder(renderFn)).toBeLessThan(
+            lastInvocationCallOrder(
+              instantSearchInstance.sendEventToInsights as jest.Mock
+            )
+          );
```
Comment (eunjae-lee) [inline src/connectors/hits/__tests__/connectHits-test.ts:830]: you think we need a test for ordering like this? @Haroenv

Comment (Haroenv) [reply src/connectors/hits/__tests__/connectHits-test.ts:830]: I wonder if there's a way to write this kind of test generically to make sure view event is *always* after render. What do you think?

**Review by Haroenv — COMMENTED** [review]
the approach works well. As it's easy to forget, the test makes sense to me. 

We need to also do this for infinite hits (maybe geo, autocomplete?)

**Review by Haroenv — APPROVED** [review]

**Review by dhayab — APPROVED** [review]
