### PR TITLE
fix(doc): ensure the documentation content doesn't overflow

### LINKED ISSUE #444: docs: When using small screens "View HTML" breaks the layout
on searchBox

It brakes with my 1440x900 resolution (chrome, macos), on the topics `searchBox` and `pagination`

It seems that long HTML lines is the main issue

### PR DESCRIPTION
**Pull request by redox**
I had a hard time finding how to fix this one :skull: 

Fix #444

(includes a fix in the indentation of the HTML code as well)

### CODE REVIEW

File: docs/js/doc.js [hunk 1]
```diff
@@ -84,7 +84,7 @@
         source += '  ';
       }
       source += line + '\n';
-      if (line.indexOf('<') === 0 && line.indexOf('</') !== 0) {
+      if (line.indexOf('<') === 0 && line.indexOf('</') !== 0 && line.indexOf('<input') === -1) {
```
Comment (pixelastic) [inline docs/js/doc.js]: Care to explain/document what this voodoo line is doing?

Comment (redox) [inline docs/js/doc.js]: It indents if the line is starting with a tag, but NOT a closing tag, and NOT a one-line tag (only `<input>` here) :)
