### PR TITLE
fix(perf): only compute snappoints when step is provided

### LINKED ISSUE #2662: Browsers crash if too many widgets are created.
**Do you want to request a *feature* or report a *bug*?**
This is a bug
 
**Bug: What is the current behavior?**
I have a case where i want to have 50 widgets, and the browser crashes. 
Edge (latest) - total page crash , Chrome (latest) - total page crash, Firefox (latest) - popup shows to wait or stop, if you wait it renders the page and up to 24 widgets.
If the widgets are 24 or less it's all good.
**Bug: What is the expected behavior?**
Browser doesn't crash if the widgets are more than 25
**Bug: What browsers are impacted? Which versions?**
Edge (latest), Chrome (latest), Firefox (latest)
**Bug: What is the proposed solution?**
 
**Feature: What is your use case for such a feature?**
I want to make a page that can filter objects that have many properties
**What is the version you are using? Always use the latest one before opening a bug issue.**
2.4.1

### PR DESCRIPTION
**Pull request by bobylito**
This keeps the snapping but does not generate the snap points if no value is provided. We can do that because rheostat snaps the point to the rounded value by default (if `snap=true`). Until rheostat provides a lazy way to fix the snappoints, there will be a risk of having an "out of memory" error because the range of values can be too big. There is an open issue opened for adding this new API: airbnb/rheostat#14 but it's uncertain if someone will work on it.

Fix #2662

### CODE REVIEW

File: src/components/Slider/Slider.js [hunk 1]
```diff
@@ -55,6 +55,7 @@ export class RawSlider extends Component {
 
   // creates an array of values where the slider should snap to
   computeSnapPoints({ min, max, step }) {
+    if(!step) return undefined;
```
Comment (iam4x) [inline src/components/Slider/Slider.js]: I think this is not valid to our linter, might do:

```js
if (step) {
  return [...range(min, max, step), max];
}
```

**Comment by iam4x** [comment]
Impressive debugging @bobylito you nailed it 💯

**Comment by bobylito** [comment]
> Anyway, according to travis you still need to update the snapshots

done

> A good workaround for now, but I wonder if an option would be to implement airbnb/rheostat#14 🤔

Yes. That could be the end game. Let's move forward with this one. I dismiss your review @Haroenv ;)
