### PR TITLE
fix(connectRefinementList): set default value for limit

### LINKED ISSUE #2504: connectRefinementList::canToggleShowMore is always true when no limit is set
The condition for `canToggleShowMore` is the following `canToggleShowMore: isShowingMore || !hasExhaustiveItems`

And `hasExhaustiveItems` is computed this way:

```js
const hasExhaustiveItems = items.length < this.getLimit();
```

If `this.getLimit() === undefined` then `hasExhaustiveItems` will be false and at the end `canToggleShowMore` would be true even if no limit has been set and there is not others available items.

This is not happening with the bundled RefinementList widget because we set by default `limit` to 10 (https://github.com/algolia/instantsearch.js/blob/develop/src/widgets/refinement-list/refinement-list.js#L231)

Should we ensure we have a default limit in the connector and update the documentation or fix the way `hasExhaustiveItems` is computed?

### PR DESCRIPTION
**Pull request by iam4x**
Fixes #2504

### CODE REVIEW

**Comment by iam4x** [comment]
Found another bug, do not merge yet 👍

**Comment by iam4x** [comment]
Should be good now @bobylito 👍

File: src/connectors/refinement-list/connectRefinementList.js [hunk 1]
```diff
@@ -58,7 +58,7 @@ export const checkUsage = ({
  * @typedef {Object} CustomRefinementListWidgetOptions
  * @property {string} attributeName The name of the attribute in the records.
  * @property {"and"|"or"} [operator = 'or'] How the filters are combined together.
- * @property {number} [limit = undefined] The max number of items to display when
+ * @property {number} [limit = 10] The max number of items to display when
  * `showMoreLimit` is not or if the widget is showing less value.
```
Comment (bobylito) [inline src/connectors/refinement-list/connectRefinementList.js]: I feel like there is a missing word here. "showMoreLimit is not **set**"

File: src/connectors/refinement-list/connectRefinementList.js [hunk 2]
```diff
@@ -328,12 +330,11 @@ export default function connectRefinementList(renderFn) {
           createURL,
           instantSearchInstance,
         } = renderOptions;
-        const items = results
-          .getFacetValues(attributeName, { sortBy })
-          .slice(0, this.getLimit())
-          .map(formatItems);
 
-        const hasExhaustiveItems = items.length < this.getLimit();
+        const rawItems = results.getFacetValues(attributeName, { sortBy });
```
Comment (bobylito) [inline src/connectors/refinement-list/connectRefinementList.js]: I wouldn't call that `rawItems` because `items` is not an unrefined state of the `items`. Why not `facetValues`?

File: src/connectors/refinement-list/connectRefinementList.js [hunk 3]
```diff
@@ -328,12 +330,11 @@ export default function connectRefinementList(renderFn) {
...
+        const items = rawItems.slice(0, this.getLimit()).map(formatItems);
+
+        const hasExhaustiveItems = rawItems.length <= this.getLimit();
```
Comment (bobylito) [inline src/connectors/refinement-list/connectRefinementList.js]: 👍
