### PR TITLE
[v1 Docs] Absolute URLs for meta images

### LINKED ISSUE #2238: [V1 Doc] use absolute link for meta image
right now the link is https://community.algolia.com/instantsearch.js/assets/instantsearch-cover-6630408f1e9eacd08a4209f803be3d43.png which is declared as /instantsearch.js/assets/instantsearch-cover-6630408f1e9eacd08a4209f803be3d43.png in the meta tag, but that doesn't work in discourse for example. 

The meta tags should be changed to absolute links instead

cc @olance

### PR DESCRIPTION
**Pull request by olance**
**Summary**
The `og:image` and `twitter:image:src` meta tags need to provide an absolute URL to be usable from external websites linking to the page.
Today, `asset_path` is used and returns a relative path, making the thumbnail broken on some websites such as our Discourse forum.

**Result**
Using `asset_url` instead of `asset_path` for `og:image` and `twitter:image:src` meta tags will output an absolute URL instead of a relative path.

Fixes #2238

### CODE REVIEW

**Comment by iam4x** [comment]
Fixes #2238

**Comment by bobylito** [comment]
@olance are you sure about `asset_url`?

**Comment by iam4x** [comment]
@bobylito Nope, local and netlify build fail.

**Comment by bobylito** [comment]
Let me know if you need a hand @olance

**Comment by olance** [comment]
@bobylito Just looked around, and the thing is `asset_url` is available in builds of `jekyll-assets` as old as a year ago, but the gem is locked to `v1.0.0` on the project. It was not available then.

**Comment by bobylito** [comment]
Can you try and update that gem?

**Comment by olance** [comment]
@bobylito yes that's what I'm looking at right now :)
I'll keep you updated!

**Comment by olance** [comment]
@bobylito @iam4x so in the end, even in latest versions Jekyll only provides a `asset_url` SASS helper but not a Liquid tag.
So I added my own :)

File: docs/_plugins/asset_url_tag.rb [hunk 1]
```diff
@@ -0,0 +1,21 @@
+module Jekyll
+  class AssetUrlTag < Liquid::Tag
+    PARAMS_RE  = / ^
+                     \s*
+                     (?: "(?<path>[^"]+)" | '(?<path>[^']+)' | (?<path>[^ ]+) )
+                     (?<attrs>.*?)
+                     (?: \[(?<options>.*)\] )?
+                     \s*
+                     $
+                   /x
```
Comment (olance) [inline docs/_plugins/asset_url_tag.rb]: This regexp comes from Jekyll's own code to parse params given to a Liquid tag

**Comment by olance** [comment]
🙌

File: docs/_plugins/asset_url_tag.rb (hunk 1 above)
Comment (bobylito) [inline docs/_plugins/asset_url_tag.rb]: Ok :)

**Comment by bobylito** [comment]
It's tedious to deploy, I'll take some time probably tomorrow.

**Comment by iam4x** [comment]
Thank's @olance :)

**Comment by olance** [comment]
my pleasure 🙃
