### PR TITLE
fix(searchBox): do not update input's value if focused

### LINKED ISSUE #163: searchBox eats characters
download

### PR DESCRIPTION
**Pull request by vvo**
fixes #163

At some point we said that there was no need to update the input while it's focused since you are typing in it. Wonder if there are some cases where this can be an issue, but since we are using the "change" helper event it should be good.

### CODE REVIEW

**Comment by redox** [comment]
:+1:

File: widgets/search-box.js [hunk 1]
```diff
@@ -56,7 +56,7 @@ function searchbox(params) {
       }
 
       helper.on('change', function(state) {
-        if (input.value !== state.query) {
+        if (input.value !== state.query && input !== document.activeElement) {
```
Comment (bobylito) [inline widgets/search-box.js]: I would check the active element first.

Comment (vvo) [inline widgets/search-box.js]: makes sense :)

Comment (vvo) [inline widgets/search-box.js]: done

**Comment by bobylito** [comment]
Cool mergin'
