### PR TITLE
fix(search-box): Fix #137 autofocus must be configurable

### LINKED ISSUE #137: [searchBox] manually focus on load when there's no query
The current `searchBox` behavior is to add `autofocus="autofocus"` to the generated or inplace searchBox.

This cannot always work because `autofocus` attribute works if you are before DOMReady/load I guess.

There's currently a bug where there is sometimes autofocus, sometimes not.

In the end here's what we should do:
- manually focus the searchBox if there's no query defined (empty query)
- do not do anything if there's already a query, most of the time it looks weird to autofocus in this case
- add an autofocus: true/false option to the searchBox (since the user cannot disable autofocus with autofocus=off now)

### PR DESCRIPTION
**Pull request by bobylito**

### CODE REVIEW

File: widgets/search-box.js [hunk 1]
```diff
@@ -60,6 +70,12 @@ function searchbox(params) {
           input.value = state.query;
         }
       });
+
+      if (autofocus === 'true' ||
```
Comment (vvo) [inline widgets/search-box.js]: does it means we are accepting people pasing autofocus: 'true'? I do not see why we would want that?

**Comment by vvo** [comment]
LGTM

**Comment by redox** [comment]
:+1:
