### PR TITLE
fix(transformData): add an explicit error message

### LINKED ISSUE #212: transformData error message
Can we put a more explicit error message when nothing is returned in the transformData function

### PR DESCRIPTION
**Pull request by redox**
In case the `transformData` is not returning any value or
the wrong type, we now throw an explicit error.

Fix #212

### CODE REVIEW

File: widgets/toggle.js [hunk 1]
```diff
@@ -104,7 +104,14 @@ function prepareToggleData(transformData) {
       count: data.count
     };
 
-    return transformData && transformData(newData) || newData;
```
Comment (redox) [inline widgets/toggle.js]: I think that `|| newData` was pretty misleading :)

File: widgets/toggle.js [hunk 2]
```diff
@@ -104,7 +104,14 @@ function prepareToggleData(transformData) {
...
+    if (transformData) {
+      newData = transformData(newData);
+      if (typeof newData !== 'object') {
+        throw new Error('`transformData` must return an object.');
+      }
+    }
```
Comment (maxiloc) [inline widgets/toggle.js]: Is this condition needed since it is handle in Template.js

Comment (redox) [inline widgets/toggle.js]: Hmmm, indeed I didn't see that it was calling the `Template`. @pixelastic do we need to call `transformData` in the widget itself?

Comment (vvo) [inline widgets/toggle.js]: That's me that did this because I needed to have a default transform data since the exposed. You should just be able to call transform data and let the template do the if throw.

**Comment by redox** [comment]
Good for you guys?

**Comment by maxiloc** [comment]
:+1:

File: components/__tests__/Template-test.js [hunk 3]
```diff
@@ -110,6 +110,34 @@ describe('Template', () => {
     expect(out).toEqual(<div dangerouslySetInnerHTML={{__html: 'it supports transformData'}}></div>);
   });
 
+  it('throws an error if the transformData is not anything', () => {
```
Comment (vvo) [inline components/__tests__/Template-test.js]: is not returning anything

File: widgets/toggle.js (hunk 1 above)
Comment (vvo) [inline widgets/toggle.js]: that was :star2: :D
