### PR TITLE
fix(sffv): when using a large limit, retain the search

### LINKED ISSUE #2156: Disabling SFFV when there are few results visible keeps it disabled in some cases
**Do you want to request a *feature* or report a *bug*?**

bug

Could you make a [jsfiddle](https://jsfiddle.net/vvoyer/0wm3donb/4/) that replicates this issue, it might be hard to find your exact use case otherwise @gabriel-kaam. Mostly how you load the extra facets.

**Bug: What is the current behavior?**

SFFV stays disabled when less than the maximum facets are visible, and more are loaded

**Bug: What is the expected behavior?**

SFFV to work when there are more than enough results

**Bug: What browsers are impacted? Which versions?**

all

**Bug: What is the proposed solution?**

Make the disabling of sffv opt-in instead of a default.

**What is the version you are using? Always use the latest one before opening a bug issue.**

v1.11.11 I guess, what version do you use @gabriel-kaam?

More detailed description at https://github.com/algolia/instantsearch.js/pull/2120#issuecomment-302405242

### PR DESCRIPTION
**Pull request by bobylito**
In the case we're using the widget with a very big limit (number of
items displayed) in the refinement list, we often still have a huge
number of items. Therefore we should be able to continue searching
in the list, even though all the items are displayed.

Fixes #2156

### CODE REVIEW

**Comment by bobylito** [comment]
Staging: http://screeching-jar.surge.sh/?query=dx&hits=3&idx=instant_search&p=0&hierarchical%5BhierarchicalCategories.lvl0%5D%5B0%5D=Cameras%20%26%20Camcorders&nR%5Bpopularity%5D%5B%3E%3D%5D%5B0%5D=0&is_v=1

In this example you can see that the filter limits the number of items in the searchable refinement lists. The bottom one doesn't prevent you from searching into it.

File: src/components/RefinementList/RefinementList.js [hunk 1]
```diff
@@ -160,13 +160,19 @@ class RefinementList extends React.Component {
...
+      searchInput = this.props.searchIsAlwaysActive ?
+        <SearchBox ref={i => { this.searchbox = i; }}
+          placeholder={this.props.searchPlaceholder}
+          onChange={this.props.searchFacetValues}
+          onValidate={() => this.refineFirstValue()}/> :
+        <SearchBox ref={i => { this.searchbox = i; }}
+          placeholder={this.props.searchPlaceholder}
+          onChange={this.props.searchFacetValues}
+          onValidate={() => this.refineFirstValue()}
+          disabled={!this.props.isFromSearch && displayedFacetValues.length < limit}/>;
```
Comment (Haroenv) [inline src/components/RefinementList/RefinementList.js]: Why not change this `this.props.isFromSearch` to be a const we decide somewhere else, based on `searchIsAlwaysActive` as well?

**Comment by bobylito** [comment]
Will merge && publish monday (too dangerous to update that before holidays)

**Comment by vvo** [comment]
Nice!

**Comment by bobylito** [comment]
Whoa that's 3 positive reviews :) Mergin' thanks for taking the time :)
